/**
 * BASE DE DADOS DE UTILIZADORES (Estático)
 * Esta lista define quem pode aceder ao sistema.
 * O 'index.html' carrega este ficheiro para o login.
 * (Formato minificado por linha, conforme solicitado).
 */

const listaDeUsuarios = [
  { "NomeCompleto": "Ana Carolina Oliveira Mattos", "Email": "ana.mattos7@portalsesisp.org.br", "RA": "4386", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Ana Luiza Benedito de Souza", "Email": "ana.souza49@portalsesisp.org.br", "RA": "3633", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Arthur Emilio Mendes Buani", "Email": "arthur.buani@portalsesisp.org.br", "RA": "421", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Benício de Melo Januário", "Email": "benicio.januario@portalsesisp.org.br", "RA": "3662", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Bruno Vinícius da Silva", "Email": "bruno.silva28@portalsesisp.org.br", "RA": "3638", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Eloah Salvato Zanchetta", "Email": "eloah.zanchetta@portalsesisp.org.br", "RA": "3672", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Emanuel dos Anjos França", "Email": "emanuel.franca@portalsesisp.org.br", "RA": "3704", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Emily Cássia do Couto", "Email": "emily.couto@portalsesisp.org.br", "RA": "4054", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Fernanda Lima Domingues", "Email": "fernanda.domingues6@portalsesisp.org.br", "RA": "3658", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Gabriela Miranda Silva", "Email": "gabriela.silva33@portalsesisp.org.br", "RA": "4384", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Guilherme Silva Lopes", "Email": "guilherme.lopes6@portalsesisp.org.br", "RA": "3659", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Henrique Siqueira Xavier de Campos", "Email": "henrique.campos3@portalsesisp.org.br", "RA": "3703", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Igor Ricardo Táparo", "Email": "igor.taparo@portalsesisp.org.br", "RA": "3675", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Isabela Rodrigues Vitalino", "Email": "isabela.vitalino@portalsesisp.org.br", "RA": "3644", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Isadora Viana Felisberto", "Email": "isadora.viana@portalsesisp.org.br", "RA": "4052", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "João Pedro Tartari", "Email": "joao.tartari2@portalsesisp.org.br", "RA": "4058", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Kevin Daniel Ferreira de Jesus", "Email": "kevin.jesus3@portalsesisp.org.br", "RA": "3677", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Kévin Paixão Gatto", "Email": "kevin.gatto@portalsesisp.org.br", "RA": "3671", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Lara Gomes Buzon", "Email": "lara.buzon@portalsesisp.org.br", "RA": "3654", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Laura Ayumi Takase", "Email": "laura.takase@portalsesisp.org.br", "RA": "3648", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Lavínie Coimbra Lilli", "Email": "lavinie.lilli@portalsesisp.org.br", "RA": "3682", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Lívia Montedioca", "Email": "livia.montedioca@portalsesisp.org.br", "RA": "4388", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Luiz Gustavo de Carvalho Brito", "Email": "luiz.brito3@portalsesisp.org.br", "RA": "3649", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Maria Eduarda Marques de Souza", "Email": "maria-souza550@portalsesisp.org.br", "RA": "4399", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Maria Eduarda Palhares", "Email": "maria.palhares@portalsesisp.org.br", "RA": "3686", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Mariana de Oliveira Ramos", "Email": "mariana.ramos@portalsesisp.org.br", "RA": "3673", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Marianna Meirelles Silva Pereira", "Email": "marianna.pereira@portalsesisp.org.br", "RA": "3685", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Marina de Paula Faria", "Email": "marina.faria@portalsesisp.org.br", "RA": "3636", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Matheus Braga de Carvalho", "Email": "matheus.carvalho14@portalsesisp.org.br", "RA": "3646", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Matheus Cardano Andrade", "Email": "matheus.cardano@portalsesisp.org.br", "RA": "3679", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Matheus Felipe dos Santos", "Email": "matheus.santos31@portalsesisp.org.br", "RA": "3681", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Nathamily de Paula Pereira", "Email": "nathamily.pereira@portalsesisp.org.br", "RA": "364", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Vítor Matheus Furtado de Oliveira", "Email": "vitor.furtado@portalsesisp.org.br", "RA": "5193", "Turma": "1A", "Perfil": "Aluno" },
  { "NomeCompleto": "Ágatha Pivati de Souza", "Email": "agatha.souza@portalsesisp.org.br", "RA": "3691", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Beatriz Barbosa Manara Rocha", "Email": "beatriz.manara@portalsesisp.org.br", "RA": "3635", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Beatriz da Silva Costa", "Email": "beatriz.costa5@portalsesisp.org.br", "RA": "3592", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Davi Soares da Silva", "Email": "davi.silva41@portalsesisp.org.br", "RA": "3787", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Eduarda Almeida Silva", "Email": "eduarda.silva94@portalsesisp.org.br", "RA": "3667", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Emilly Dentini Lopes", "Email": "emilly.dentini@portalsesisp.org.br", "RA": "3652", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Érick Martins da Costa", "Email": "erick.costa@portalsesisp.org.br", "RA": "3676", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Felipe Gabriel Gonçalves", "Email": "felipe.goncalves6@portalsesisp.org.br", "RA": "3536", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Gabriel Alves da Silva", "Email": "gabriel.silva68@portalsesisp.org.br", "RA": "3664", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Gabriella Ramos Tirapélle", "Email": "gabriella.tirapelle@portalsesisp.org.br", "RA": "3645", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Isabela Ferreira Bernardo", "Email": "isabela.bernardo@portalsesisp.org.br", "RA": "3661", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Isabella Lopes de Carvalho", "Email": "isabella.carvalho5@portalsesisp.org.br", "RA": "3651", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Isabelly Maria Pereira", "Email": "isabelly.pereira@portalsesisp.org.br", "RA": "3687", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "João Vítor Favareto Openheimer", "Email": "joao.openheimer@portalsesisp.org.br", "RA": "3674", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Laís Couto", "Email": "lais.couto@portalsesisp.org.br", "RA": "3684", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Lucas Stein Balbino", "Email": "lucas.balbino@portalsesisp.org.br", "RA": "3663", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Luiz Octávio Tozo", "Email": "luiz.tozo@portalsesisp.org.br", "RA": "367", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Maria Eduarda de Campos Quintilhano", "Email": "maria.quintilhano@portalsesisp.org.br", "RA": "3705", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Maria Eduarda Parmezani Cardoso", "Email": "maria.parmezani@portalsesisp.org.br", "RA": "3689", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Maria Isabella Francisco da Silva", "Email": "maria.silva229@portalsesisp.org.br", "RA": "4057", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Murillo Henrique Silva Lima", "Email": "murillo.lima3@portalsesisp.org.br", "RA": "3641", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Murilo Henrique Cardoso dos Santos", "Email": "murilo.santos102@portalsesisp.org.br", "RA": "4055", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Natália Lopes Ramos", "Email": "natalia.lopes@portalsesisp.org.br", "RA": "3539", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Nicolas de Moraes Ferrari", "Email": "nicolas.ferrari@portalsesisp.org.br", "RA": "3544", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Pedro Del Santo Bordignon", "Email": "pedro.bordignon@portalsesisp.org.br", "RA": "4131", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Samuel David Bitencourt de Sousa", "Email": "samuel.sousa27@portalsesisp.org.br", "RA": "3668", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Sophia Campos Ferreira e Silva", "Email": "sophia.silva42@portalsesisp.org.br", "RA": "3583", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Thalita Cristina Vercelino Fernandes", "Email": "thalita.fernandes@portalsesisp.org.br", "RA": "5026", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Victória Cavassini Santos", "Email": "victoria.santos49@portalsesisp.org.br", "RA": "5044", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Vítor Augusto Prado", "Email": "vitor.prado3@portalsesisp.org.br", "RA": "5043", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Vítor Hugo Elisiário", "Email": "vitor.elisiario@portalsesisp.org.br", "RA": "5042", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Vitória Freitas Gonzaga de Souza", "Email": "vitoria.gonzaga@portalsesisp.org.br", "RA": "5041", "Turma": "1B", "Perfil": "Aluno" },
  { "NomeCompleto": "Alana Beatriz Moreira", "Email": "alana.moreira@portalsesisp.org.br", "RA": "3636", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Ana Clara Franco de Campos Batista", "Email": "ana.batista45@portalsesisp.org.br", "RA": "3607", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Ana Laura do Nascimento", "Email": "ana.nascimento17@portalsesisp.org.br", "RA": "4466", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Beatriz Vieira da Silva", "Email": "beatriz.silva75@portalsesisp.org.br", "RA": "3567", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Bruno Henrique Rosa Antonio", "Email": "bruno-antonio280@portalsesisp.org.br", "RA": "4314", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Bruno Ramos Bratfisch", "Email": "bruno.bratfisch@portalsesisp.org.br", "RA": "4151", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Calebe Cordeiro Gino", "Email": "calebe.gino@portalsesisp.org.br", "RA": "3606", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Davi Emanuel Salvato Zanchetta", "Email": "davi.zanchetta@portalsesisp.org.br", "RA": "3542", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Francisco Villa Verde", "Email": "francisco.verde@portalsesisp.org.br", "RA": "3566", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Gabriel Viotto Oliveira", "Email": "gabriel.oliveira5@portalsesisp.org.br", "RA": "3563", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Guilherme Farias Kochinski", "Email": "guilherme.kochinski@portalsesisp.org.br", "RA": "4214", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Guilherme Junho Teixeira Fernandes", "Email": "guilherme-fernandes560@portalsesisp.org.br", "RA": "4397", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "João Gabriel Mendes", "Email": "joao.mendes@portalsesisp.org.br", "RA": "3575", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Júlia Alves Lima", "Email": "julia.lima17@portalsesisp.org.br", "RA": "3202", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Lavínia Bueno Ferreira", "Email": "lavinia.ferreira@portalsesisp.org.br", "RA": "3586", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Lorena Almeida Correa Silva", "Email": "lorena.correa@portalsesisp.org.br", "RA": "3942", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Lorena de Araujo Noriega Picoli", "Email": "lorena.noriega@portalsesisp.org.br", "RA": "4392", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Lorrainny Fernanda Ribeiro do Couto", "Email": "lorrainny.couto@portalsesisp.org.br", "RA": "4398", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Luiz Otávio Fazullo da Silva", "Email": "luiz.fazullo@portalsesisp.org.br", "RA": "3598", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Maria Eduarda Saquette Silva", "Email": "maria.saquette@portalsesisp.org.br", "RA": "361", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Milena Busso Chicarelli", "Email": "milena.chicarelli@portalsesisp.org.br", "RA": "4654", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Moisés Montini Kemp", "Email": "moises.kemp@portalsesisp.org.br", "RA": "3593", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Nicole Pelegrini Fernandes", "Email": "nicole.pelegrini@portalsesisp.org.br", "RA": "3557", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Nicolly Núbia de Oliveira Santos", "Email": "nicolly.santos3@portalsesisp.org.br", "RA": "3700", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Odair Henrique Cavalheiro", "Email": "odair.cavalheiro@portalsesisp.org.br", "RA": "3552", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Otávio Henrique Martins", "Email": "otavio.martins@portalsesisp.org.br", "RA": "3579", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Pedro Henrique Pelegrini Batista", "Email": "pedro.pelegrini@portalsesisp.org.br", "RA": "3572", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Ryan Paulo Parreira Gimenes", "Email": "ryan.gimenes@portalsesisp.org.br", "RA": "3694", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Valentina Barão Obole", "Email": "valentina-obole890@portalsesisp.org.br", "RA": "4313", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Victor Hugo Gomes dos Santos", "Email": "victor.santos30@portalsesisp.org.br", "RA": "4128", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Vinícius Siqueira de Arruda", "Email": "vinicius-arruda955@portalsesisp.org.br", "RA": "4038", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Matheus Rodrigues Costa", "Email": "matheus.costa11@portalsesisp.org.br", "RA": "3581", "Turma": "2A", "Perfil": "Aluno" },
  { "NomeCompleto": "Ana Lívia Silveira de Moraes", "Email": "ana.moraes30@portalsesisp.org.br", "RA": "4059", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Arthur Braga", "Email": "arthur.braga@portalsesisp.org.br", "RA": "3448", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Brenda Maria de Carvalho Moraes", "Email": "brenda.moraes@portalsesisp.org.br", "RA": "354", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Eduarda Caroline Fernandes", "Email": "eduarda.fernandes3@portalsesisp.org.br", "RA": "4127", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Gabrielly Vitória Rodrigues Da Silva", "Email": "gabrielly.silva5@portalsesisp.org.br", "RA": "3584", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Guilherme Ronan Contessotto", "Email": "guilherme.contessoto@portalsesisp.org.br", "RA": "3551", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Heloísa Gabriela Oliveira da Silva", "Email": "heloisa.silva2@portalsesisp.org.br", "RA": "3616", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Isadora da Silva Barros", "Email": "isadora.barros@portalsesisp.org.br", "RA": "4042", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Jefferson Silva Santon", "Email": "jefferson.santon@portalsesisp.org.br", "RA": "3545", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "João Felipe Kaiser de Senna", "Email": "joao.senna@portalsesisp.org.br", "RA": "3562", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "João Pedro Inácio da Silva", "Email": "joao.inacio@portalsesisp.org.br", "RA": "4027", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Júlia Mendes Santos", "Email": "julia.santos136@portalsesisp.org.br", "RA": "3953", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Larissa Miranda de Conti", "Email": "larissa.conti@portalsesisp.org.br", "RA": "414", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Laura Capra", "Email": "laura.capra@portalsesisp.org.br", "RA": "3612", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Lauren Pinheiro", "Email": "lauren.pinheiro@portalsesisp.org.br", "RA": "3609", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Leonardo Bovolenta Zuliani", "Email": "leonardo.zuliani@portalsesisp.org.br", "RA": "3574", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Letícia Ferro da Silva", "Email": "leticia.ferro@portalsesisp.org.br", "RA": "3626", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Luana Caroline dos Santos", "Email": "luana.caroline@portalsesisp.org.br", "RA": "3547", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Marcelo Lopes", "Email": "marcelo.lopes@portalsesisp.org.br", "RA": "3868", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Marcio Augusto Lelis Gazito Castiglioni", "Email": "marcio.castiglioni@portalsesisp.org.br", "RA": "356", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Maria Clara da Silva", "Email": "maria.silva230@portalsesisp.org.br", "RA": "3597", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Marianne Nunes da Rocha", "Email": "marianne.rocha@portalsesisp.org.br", "RA": "3568", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Miguel Pereira da Silva", "Email": "miguel.silva6@portalsesisp.org.br", "RA": "3585", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Natália Aparecida Pinto", "Email": "natalia.aparecida@portalsesisp.org.br", "RA": "4653", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Nicolas Sebastian de Oliveira", "Email": "nicolas.sebastian@portalsesisp.org.br", "RA": "3558", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Otavio Palma Teixeira", "Email": "otavio.teixeira@portalsesisp.org.br", "RA": "3605", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Pedro Henrique Costa Quintilhano", "Email": "pedro.quintilhano@portalsesisp.org.br", "RA": "3559", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Pedro Henrique de Lima", "Email": "pedro.lima10@portalsesisp.org.br", "RA": "3549", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Tairone Bruno Batista", "Email": "tairone.batista@portalsesisp.org.br", "RA": "5022", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Vinycius Gabriel Fernandes Correa", "Email": "vinycius.correa@portalsesisp.org.br", "RA": "3603", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "Vítor Henrique dos Santos", "Email": "vitor.santos19@portalsesisp.org.br", "RA": "4029", "Turma": "2B", "Perfil": "Aluno" },
  { "NomeCompleto": "William Ricardo Fogo Onofre", "Email": "william.onofre@portalsesisp.org.br", "RA": "3573", "Turma": "2B", "Perfil": "Aluno" },
  // Professor (adicionado da sua lista)
  { "NomeCompleto": "Geovane Módena", "Email": "geovane.modena@portalsesisp.org.br", "RA": "9999", "Turma": "", "Perfil": "Professor" }
];

// Torna a variável 'listaDeUsuarios' acessível globalmente
// O 'index.html' irá ler esta variável.
window.listaDeUsuarios = listaDeUsuarios;
